import React from 'react';
import { Page, Text, View, Document, StyleSheet, Image } from '@react-pdf/renderer';

import MiniLogo from '../static/images/minilogo.png'

// Create styles
const styles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: 'white',
    color: '#316993',
    margin: '20rem'
  },
  group: {
    margin: '10rem 0'
  },
  groupName: {
    fontFamily: 'Helvetica',
    marginBottom: '10em',
    fontSize: 14
  },
  className: {
    fontFamily: 'Helvetica-Bold',
    margin: '40rem 0'
  },
  groups: {
    fontFamily: 'Helvetica-Bold',
    margin: '10rem 0'
  },
  membersQty: {
    fontSize: 14,
    border: '2pt solid #316993',
    width: '120em',
    paddingLeft: '10em',
    paddingTop: '5em',
    paddingBottom: '5em',
    marginLeft: '20em',
    marginBottom: '10em',
  },
  memberName: {
    fontSize: 14,
    border: '2pt solid #316993',
    width: '520rem',
    paddingLeft: '15em',
    paddingTop: '5em',
    paddingBottom: '5em',
    marginLeft: '20em'
  },
  logoHeader: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center'
  },
  logo: {
    width: '40rem',
    height: '40rem',
    marginRight: '10rem'
  },
  generatedMessage: {
    fontSize: 13,
    fontFamily: 'Helvetica-Bold',
    marginTop: '20em'
  }
});

// Create Document Component
function GroupListPDF(props) {
  const {name, groups} = props

  const generateGroupsMarkup = (groups) => groups.map((group, groupIndex) => (
    <View style={styles.group} key={groupIndex}>
      <Text style={styles.groupName}>Grupo {group.idGroup}: </Text>
      <View>
        <Text style={styles.membersQty}>{group.members.length} participante{group.members.length !== 1 ? 's' : ''}</Text>
        { group.members.map((member, memberIndex) => (
          <Text key={memberIndex + groupIndex} style={styles.memberName}>{member.name}</Text>
        )) }
      </View>
    </View>
  ))

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <View style={styles.logoHeader}>
            <Image src={MiniLogo} style={styles.logo} />
            <Text style={styles.className}>{name}</Text>
          </View>
          <Text style={styles.groups}>GRUPOS</Text>
        </View>
        <View style={styles.groupsContainer}>
          {generateGroupsMarkup(groups)}
        </View>
        <View>
          <Text style={styles.generatedMessage}>Generated by Tchimo</Text> 
        </View>
      </Page>
    </Document>
  )

}

export default GroupListPDF